FROM python:3.13.9-alpine3.22 AS base

RUN apk update && apk upgrade --no-cache
RUN pip install --no-cache-dir --upgrade pip uv

WORKDIR /app
COPY . .

RUN uv sync --extra streamlit

EXPOSE 9001

CMD ["uv", "run", "streamlit", "run", "sl.py", \
     "--server.address", "0.0.0.0", \
     "--server.port", "9001"]
