FROM python:3.13.9-alpine3.22 AS base

RUN apk update && apk upgrade --no-cache

WORKDIR /app
COPY streamlit/main.py /app/

# not installing uv because no dependencies list

RUN pip install --no-cache-dir --upgrade pip && \
    pip install streamlit

EXPOSE 9001

CMD ["streamlit", "run", "main.py", \
     "--server.address", "0.0.0.0", \
     "--server.port", "9001"]
