FROM python:3.13.9-alpine3.22 AS base

RUN apk update && apk upgrade --no-cache
RUN pip install --no-cache-dir --upgrade pip uv

WORKDIR /app
COPY . .

RUN uv sync --extra fastapi

EXPOSE 9000

CMD ["uv", "run", "fastapi", "dev", "fa.py", \
    "--host", "0.0.0.0", \
    "--port", "9000", \
    "--reload"]

#CMD ["fastapi", "dev", "fastapi.py", \
#     "--host", "0.0.0.0", \
#     "--port", "9000"]
