name: Build and Push Containers
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  permissions:
    id-token: write
    contents: read
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Assume STS role
      uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN }}
          aws-region: us-east-1
          role-session-name: github-actions
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build and push FastAPI container
      run: |
        docker build -f Dockerfile-fa.yml -t ${{ steps.login-ecr.outputs.registry }}/fastapi:${{ github.sha }} .
        docker push ${{ steps.login-ecr.outputs.registry }}/fastapi:${{ github.sha }}
    - name: Build and push streamlit container
      run: |
        docker build -f Dockerfile-sl.yml -t ${{ steps.login-ecr.outputs.registry }}/streamlit:${{ github.sha }} .
        docker push ${{ steps.login-ecr.outputs.registry }}/streamlit:${{ github.sha }}
