name: Build and Push Containers
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Assume STS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN }}
          aws-region: us-east-1
          role-session-name: github-actions
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push FastAPI container
        run: |
          docker build -f Dockerfile-fa.yml \
            -t ${{ steps.login-ecr.outputs.registry }}/fa:${{ github.sha }} \
            -t ${{ steps.login-ecr.outputs.registry }}/fa:latest \
            .
          docker push ${{ steps.login-ecr.outputs.registry }}/fa:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/fa:latest
      - name: Build and push streamlit container
        run: |
          docker build -f Dockerfile-sl.yml \
            -t ${{ steps.login-ecr.outputs.registry }}/sl-image:${{ github.sha }} \
            -t ${{ steps.login-ecr.outputs.registry }}/sl-image:latest \
            .
          docker push ${{ steps.login-ecr.outputs.registry }}/sl-image:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/sl-image:latest
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster streamlit-cluster \
            --service streamlit-service \
            --force-new-deployment
